### PR TITLE
Feature/243

### LINKED ISSUE #243: Change heat maps to contour plots in 2D visualization
Screenshot 2023-02-24 at 08 42 51
The client want to change the heatmaps into contour plots (see example attached). I am assuming the new contour maps will come from @stephenlenzi and then we will need to change the FE menu

### PR DESCRIPTION
**Pull request by afonsobspinto**
Closes #243, #242 and #274
It seems like some of my previous PR's, by mistake, did not get merged into develop so this one includes them as well.

Upon deployment we will need to (which I did on dev):
- Regenerate the plots for all populations (update_populations_static_images)
- Update cells of residential populations (reset_residential_populations)

Implemented solution:
- Replaces probability map creator with a contour plot creator
- Upscale the atlas by 4x for plot generation (atlas_upscale_service)
- Updates 3D meshes
- Updates residential population files
- Modifies 2D Viewer to show dropdown instead of switch for the contour plot
- Updates drawColoredImage to consider original image pixel intensity

Other changes explained: 
- Renames a couple of methods and variables to be consistent with the nomenclature (f.e. annotation_image to grey_and_white_matter_images, subsegment to subdivision)
- Updates api (renames probability_map endpoint to contour_plot; adds residential endpoint)
- Removes deprecated atlas annotation tweaks and converges atlas wrapper to match with latest cordmap
- Refactors out common methods of density map plots 
- Adds comments for a couple of methods
- Adds django management command to facilitate the update of residential populations
- Adds django management command to facilitate the update of population cells
- Adds django management command to regenerate plots
- Updates models to allow the existence of populations without experiments
- Refactors out cordmap utilities to a separated service (sometimes copying code from cordmap)
- Uses above service in detriment of launching a new workflow upon file uploads. This improves user feedback
- Fixes version of potential conflicting packages (django and djangorestframework)
- Updates to latest geppetto-meta
- Has frontend app fetching for residential populations on Mount
- Updates frontend sidebar to show residential populations
- Updates codefresh dev to work with 

How to test this PR: 
- 2D viewer should allow you to display contours and/or heatmaps:
image
image

- Both 3D and 2D should seem smoother:
3D before:
image
3D after:
image

2D before:
image
2D after:
image

### Sanity checks:
- [x] The pull request is explicitly linked to the relevant issue(s)
- [x] The issue is well described: clearly states the problem and the general proposed solution(s)
- [x] From the issue and the current PR it is explicitly stated how to test the current change
- [x] The labels in the issue set the scope and the type of issue (bug, feature, etc.)
- [x] All the automated test checks are passing
- [ ] All the linked issues are included in one milestone
- [x] All the linked issues are assigned

### Breaking changes (select one):
- [x] The present changes do not change the preexisting api in any way
- [ ] This PR and the issue are tagged as a `breaking-change`

### Possible deployment updates issues (select one):
- [ ] There is no reason why deployments may break after the current update
- [x] This PR and the issue are tagged as `alert:deployment`

### Test coverage (select one):
- [ ] Tests for the relevant cases are included in this pr
- [x] The changes included in this pr are out of the current test coverage scope

### Documentation (select one):
- [ ] The documentation has been updated to match the current changes
- [x] The changes included in this PR are out of the current documentation scope

### CODE REVIEW

**Review by zsinnema — COMMENTED** [review]
Hi @afonsobspinto, question. Did you on purpose check in all assets? I though they are generated on build.

Another question is why do I see so many (old) commits?

**Comment by afonsobspinto** [comment]
Yes. The assets added (meshes and residential populations) are not generated on build (opposed to the static images as you referred). There are historical reasons for this different behaviour but I believe they no longer apply so we might be able to also generate the aforementioned at the build time. I'm opening https://github.com/MetaCell/salk-interactive-atlas/issues/276 to handle that.

There might be 2 reasons for that:
- As mentioned in the description, I believe this PR contains the content of other PR's that were meant to merged into develop but weren't (by mistake)
- The work on the issues addressed on this PR started some time ago but due to a period of holidays of the different members involved in the project we are only finishing now

**Comment by afonsobspinto** [comment]
I'm temporarily moving the PR to a draft state so that we don't risk triggering an automatic deployment upon merge that would affect the demo in today's sprint meeting. I will move it back to ready for review later on

**Comment by zsinnema** [comment]
@afonsobspinto is it correct that the assets of cordmap 10u should be in Git?

**Comment by zsinnema** [comment]
@afonsobspinto same for the "residential" populations. Suggestion: we don't store in Git things that can be generated

**Comment by afonsobspinto** [comment]
See #315

**Review by zsinnema — APPROVED** [review]

**Pull request merged**
